<a href="https://colab.research.google.com/github/iseoyeon408/2026-BigDataAnalyticsProgramming/blob/main/03w_numpy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.ndarray((2, 3))
a

array([[1.65664725e-315, 0.00000000e+000, 5.78916875e-317],
       [6.62707365e-310, 6.62707365e-310, 6.62707365e-310]])

In [2]:
import numpy as np

a = np.ndarray((3, 2), dtype = int)
a

array([[      335309136,               0],
       [       11717408, 134133464027120],
       [134133464027168, 134133464027024]])

In [3]:
a = np.ndarray((3, 2), int)
a

array([[      337184588,               0],
       [134133461906944, 134133461906992],
       [134133461411888, 134133756159216]])

In [4]:
import numpy as np
a = np.array([1, 2, 3], dtype = int)
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [6]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [8]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


In [10]:
import numpy as np
np.linspace(2, 3)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [11]:
(3-1)/(50-1)

0.04081632653061224

In [16]:
np.linspace(2, 3, 2)

array([2., 3.])

In [17]:
np.linspace(2, 3, 3)

array([2. , 2.5, 3. ])

In [19]:
np.linspace(2, 3, 3, retstep = True)
a[1]

np.int64(2)

In [20]:
np.linspace(2, 3, 3, retstep = True)

(array([2. , 2.5, 3. ]), np.float64(0.5))

In [21]:
np.linspace(2, 3, 3, retstep = True, endpoint= False)

(array([2.        , 2.33333333, 2.66666667]), np.float64(0.3333333333333333))

In [22]:
(3-2)/3

0.3333333333333333

## numpy 주요함수

In [25]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [26]:
np.zeros((2, 3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [27]:
np.zeros(2, 3)

TypeError: Cannot interpret '3' as a data type

In [28]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.full([2, 3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [30]:
np.full((2, 3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
np.arange

In [33]:
np.full((4, 3), np.arange(4). reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

## 고급 색인

In [34]:
import numpy as np

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
x[1]

np.int64(1)

In [36]:
x[:5]

array([0, 1, 2, 3, 4])

In [37]:
x[2]

np.int64(2)

In [41]:
x[ [2] ]

array([2])

In [42]:
x[ [2, 3]]

array([2, 3])

In [43]:
x[2, 3]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [44]:
x[ [2, 3, 2, 4, 8]]

array([2, 3, 2, 4, 8])

In [45]:
x = np.arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [46]:
x[0, 1]

np.int64(1)

In [48]:
int(x[0,1])

1

In [50]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [51]:
x[, 2:8]

SyntaxError: invalid syntax (664993225.py, line 1)

In [52]:
x[..., 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [53]:
x[0,1]

np.int64(1)

In [54]:
x[[0],[1]]

array([1])

In [56]:
x[[0,1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [57]:
x[[1, 3, 5]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [59]:
x[[1, 3, 5], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [60]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [61]:
x[ [1, 3], [2, 2]]

array([10, 26])

In [62]:
x[ [1, 3], [2]]

array([10, 26])

In [63]:
x[ [1, 3], [2, 3]]

array([10, 27])

In [64]:
x[[0, 2, 4], 1]

array([ 1, 17, 33])

In [65]:
x[[0, 2, 4], [1]]

array([ 1, 17, 33])

In [66]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [67]:
x[[0, 2, 4], :2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [68]:
x[[0, 2, 4], [1, 1, 1]]

array([ 1, 17, 33])

In [69]:
x[[0, 2, 4], [1, 1]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [70]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [71]:
a = np.arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [72]:
a[2: 4, 3: 7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [73]:
a[np.arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [74]:
a[[2, 3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [75]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [76]:
a[np.arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [79]:
a[np.arange(2, 4)][:, [1, 0]]

array([[17, 16],
       [25, 24]])

In [80]:
a[np.arange(2, 4)][:, [1,1, 1]]

array([[17, 17, 17],
       [25, 25, 25]])

In [81]:
a[np.arange(2, 4)][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29]])

In [82]:
a[np.arange(2, 4)][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29]])

In [83]:
a[[2, 3, 4]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [86]:
a[np.arange(2, 5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [87]:
a[[2, 3, 4]][:, [-1, -2, -3, -4, -5, -6, -7]]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

In [88]:
a[[2, 3, 4]][:, np.arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

## 종료