<a href="https://colab.research.google.com/github/iseoyeon408/2026-BigDataAnalyticsProgramming/blob/main/04w_array_stack_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

a = np.arange(1, 13). reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
c = np.arange(1, 6, 2)
c


array([1, 3, 5])

In [10]:
import numpy as np

np.hstack((a, np.expand_dims(c, axis = 1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [11]:
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [12]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
np.column_stack( (a, b) )

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])
x

array([[1, 2, 3]])

In [15]:
y

array([[4, 5, 6]])

In [16]:
x.shape, y.shape

((1, 3), (1, 3))

In [18]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [19]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [20]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [21]:
np.column_stack( (x, 10, 20, y) )

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [23]:
import numpy as np

rg = np.random.default_rng(12345)
rg.random()   #[0,1)

0.22733602246716966

In [24]:
rg.random()

0.31675833970975287

In [25]:
rg.random(5)

array([0.79736546, 0.67625467, 0.39110955, 0.33281393, 0.59830875])

In [26]:
rg.random((3, 4))

array([[0.18673419, 0.67275604, 0.94180287, 0.24824571],
       [0.94888115, 0.66723745, 0.09589794, 0.44183967],
       [0.88647992, 0.6974535 , 0.32647286, 0.73392816]])

In [27]:
rg.random((2, 3, 4))

array([[[0.22013496, 0.08159457, 0.1598956 , 0.34010018],
        [0.46519315, 0.26642103, 0.8157764 , 0.19329439],
        [0.12946908, 0.09166475, 0.59856801, 0.8547419 ]],

       [[0.60162124, 0.93198836, 0.72478136, 0.86055132],
        [0.9293378 , 0.54618601, 0.93767296, 0.49498794],
        [0.27377318, 0.45177871, 0.66503892, 0.33089093]]])

In [30]:
import numpy as np

rg = np.random.default_rng(1)
rg.integers(low = 0, high = 10 ,size = 3)  #[10,0)정수난수

array([4, 5, 7])

In [35]:
rg.integers(1, 7, (3, 4))

array([[1, 3, 6, 1],
       [3, 3, 6, 2],
       [4, 2, 1, 5]])

In [33]:
import numpy as np

rg = np.random.default_rng(1)
rg.standard_normal(3) # 표준 정규분포 실수 난수

array([0.34558419, 0.82161814, 0.33043708])

In [34]:
rg.standard_normal((4, 3))  # 표준 정규분포 실수 난

array([[-1.30315723,  0.90535587,  0.44637457],
       [-0.53695324,  0.5811181 ,  0.3645724 ],
       [ 0.2941325 ,  0.02842224,  0.54671299],
       [-0.73645409, -0.16290995, -0.48211931]])

## 배열 결합 연습

In [2]:
import numpy as np

a = np.arange(1, 4)
b = np.arange(4, 7)
c = np.arange(7, 10)
a, b, c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [3]:
p = np.arange(1, 7).reshape(2, 3)
q = np.arange(11, 17).reshape(2, 3)
r = np.arange(21, 27).reshape(2, 3)
p, q, r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [4]:
np.vstack((a, b, c)) #1D --> 2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.vstack((p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [6]:
np.hstack((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
p, q, r


(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [8]:
np.hstack((p, q, r))

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [9]:
a, b, c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [10]:
np.column_stack((a, b, c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [11]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.concatenate((a, b, c), axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [14]:
np.concatenate((a, b, c), axis = None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.concatenate((a, b, c), axis = -1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
p, q, r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [17]:
np.concatenate((p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [18]:
np.concatenate((p, q, r), axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [19]:
np.concatenate((p, q, r), axis = 1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [20]:
np.concatenate((p, q, r), axis = -1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [21]:
np.concatenate((p, q, r), axis = None)

array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25,
       26])

In [23]:
np.c_[a, b, c]

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [25]:
np.column_stack((a, b, c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [26]:
np.column_stack([a, b, c])

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [28]:
np.c_[p, q, r]  #2D --> 2D

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [29]:
np.column_stack([p, q, r])

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [30]:
np.r_[a, b, c] #1D --> 1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.r_[p, q, r]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [33]:
np.vstack((p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])